version: '3.8'

services:
  clean-architecture.api:
    build:
      context: ./
      dockerfile: Dockerfile.debug
      network: host
      args:
        DOTNET_CONFIG: Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw