version: '3.8'

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=helloWorldDb
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    tty: true
  clean-architecture.api:
    ports:
      - "5999:80"
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./CleanArchitecture.Api/:/src/
    tty: true